name: SimpleSpawners
main: com.github.exobite.mc.simplespawners.PluginMaster
version: ${project.version}
author: ExoBiTe
website: https://www.spigotmc.org/resources/108088/
description: Customizable Spawners
api-version: 1.17
softdepend: [Vault, PlaceholderAPI]

commands:
  SimpleSpawners:
    description: SimpleSpawners Main Command
    usage: /SimpleSpawners
    aliases: ss

permissions:
  simplespawners.*:
    default: op
    children:
      simplespawners.cmd.*: true
      simplespawners.interact.changespawner: true
      simplespawners.interact.nofees: true
      simplespawners.mine.*: true

  simplespawners.cmd.*:
    default: op
    children:
      simplespawners.cmd.give: true
      simplespawners.cmd.reload: true

  simplespawners.cmd.reload:
    description: Allows usage of /SimpleSpawners reload

  simplespawners.cmd.give:
    description: Allows usage of /SimpleSpawners give

  simplespawners.interact.changespawner:
    description: Allows to change the Spawned Entity for MobSpawners

  simplespawners.interact.nofees:
    description: Players with this Permission don't have to pay for any Spawner Change

  simplespawners.mine.*:
    default: op
    children:
      simplespawners.mine.natural: true
      simplespawners.mine.custom: true

  simplespawners.mine.natural:
    description: Allows to break Natural Mob Spawners with a Silk Touch Pickaxe

  simplespawners.mine.custom:
    description: Allows to break Natural Mob Spawners with a Silk Touch Pickaxe

  simplespawners.ignoreblacklist:
    description: Allows to set blacklisted Entities to spawners